url: "https://julianjarjour.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "julian jarjour" # the name of your site, e.g. ACME Corp.
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
plugins:
  - jekyll-gallery-generator

permalink: /posts/:title

collections:
  notes:
    output: true

gallery:
  dir: photos # Path to the gallery
  symlink: false # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "photos" # Title for gallery index page
  title_prefix: "" # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field:
    "date_time" # How to sort galleries on the index page.
    # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: # max width of thumbnails (in pixels)
    y: 930 # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    flower_hue_shift:
      best_image: 0001.jpg
      info:
        desc: "<p>These photos didn't come out to my liking, and in such cases I like to mess around in post. I landed on this hue shift effect that reminded me of <a href='https://en.wikipedia.org/wiki/Fantastic_Planet' target='_blank'>Fantastic Planet.</a></p>"
    harry_skates:
      best_image: 0008.jpg
      info:
        desc: "<p>At the Boston Common with Harry McIntyre, who just released their debut album <a href='https://releasethedistraction.bandcamp.com/album/release-the-distraction' target='_blank'>Release The Distraction!</a></p><p>I took the album's cover photo (a photo of a polaroid) on this day and we ate super chimichangas at El Jefe's Taqueria. They were good.</p>"
    beware_of_denise:
      best_image: 0010.jpg
      info:
        desc: "<p>ZUMIX band Beware of Denise performs at Tall Ship Boston. This was their second-to-last gig with this lineup before Wendy graduated.</p>"
    ethereal_day:
      best_image: 0006.jpg
      info:
        desc: "<p>These were taken on a calm day along the Northern Strand Community Trail. Abby and I were collecting rocks by the marsh and we found a dead crab, whose claws she tore off.</p>"
    to_the_park:
      best_image: 0007.jpg
    kotoko_brass:
      best_image: 0003.jpg
      info:
        desc: "<p>Kotoko Brass performing at Piers Park to close out the ZUMIX Summer Concert Series.</p>"
    reSET_boygenius:
      best_image: 0014.jpg
      info:
        desc: "<p>These were shot at the new Suffolk Downs venue, creatively named &ldquo;The Stage.&rdquo; I was volunteering at the ZUMIX booth with Nora and Tiffany in the first half and managed to get a media pass (my first-ever) thanks to Madeleine!</p><p>The show was part of the Re:SET Concert Series and featured Bartees Strange, Dijon, Clairo, and boygenius.</p>"
    co23_grad:
      best_image: 0007.jpg
      info:
        desc: "<p>Lynn Classical High School's Class of 2023 graduates. The band and choir performed some tunes as part of the ceremony.</p>"
