url: "https://julianjarjour.vercel.app/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "julian jarjour" # the name of your site, e.g. ACME Corp.
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-gallery-generator

gallery:
  dir: photos # Path to the gallery
  symlink: false # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "photos" # Title for gallery index page
  title_prefix: "" # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field:
    "date_time" # How to sort galleries on the index page.
    # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: # max width of thumbnails (in pixels)
    y: 834 # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    flower_hue_shift:
      best_image: 0003.jpg
    harry_skates:
      best_image: 0004.jpg
    beware_of_denise:
      best_image: 0010.jpg
      info:
        desc: "ZUMIX band Beware of Denise performs at Tall Ship Boston. This was their second-to-last gig with this lineup before their singer, Wendy, graduated."
    ethereal_day:
      best_image: 0006.jpg
